-- * 연습문제
DROP TABLE MEMBER;
DROP TABLE MEMBER_LEVEL;
DROP SEQUENCE MEMBER_SQ;
CREATE TABLE MEMBER_LEVEL(
    LEVELNO NUMBER(5) PRIMARY KEY,
    LEVELNAME VARCHAR(50) NOT NULL
);
CREATE TABLE MEMBER(
    mNO NUMBER(5) PRIMARY KEY,
    mNAME VARCHAR2(30) NOT NULL,
    mPW VARCHAR2(30) CHECK( LENGTH(mPW) BETWEEN 1 AND 8),
    mEMAIL VARCHAR2(50) UNIQUE,
    mPOINT NUMBER(5) CHECK(mPOINT>=0),
    mRDATE DATE DEFAULT SYSDATE,
    LEVELNO REFERENCES MEMBER_LEVEL(LEVELNO)
);
CREATE SEQUENCE MEMBER_SQ 
    MAXVALUE 99999
    NOCACHE NOCYCLE;

INSERT INTO MEMBER_LEVEL VALUES(-1, 'black');
INSERT INTO MEMBER_LEVEL VALUES(0, '일반');
INSERT INTO MEMBER_LEVEL VALUES(1, '실버');
INSERT INTO MEMBER_LEVEL VALUES(2, '골드');

INSERT INTO MEMBER VALUES( MEMBER_SQ.nextval,'홍길동', 'aa', 'hong@hong.com', 0, TO_DATE('24/09/26','YY/MM/DD'), 0);
INSERT INTO MEMBER VALUES(MEMBER_SQ.nextval,'신길동', 'bb', 'sin@sin.com', 1000, TO_DATE('22/04/01', 'YY/MM/DD'), 1);
desc member;
-- 연습문제와 같이 출력되도록 SELECT (EQUI JOIN)
SELECT mNO, mNAME, TO_CHAR(mRDATE, 'YYYY-MM-DD') mRDATE, mEMAIL, mPOINT point, LEVELNAME levelname FROM MEMBER M , MEMBER_LEVEL ML WHERE M.LEVELNO = ML.LEVELNO;