-- 3. 'main' 재료 추가
INSERT INTO ingredients (ingredient_name, ingredient_category) VALUES
('돼지고기(목살)', 'main'), ('양파', 'main'), ('대파', 'main'), ('두부', 'main'), ('김치', 'main'), ('애호박', 'main'), 
('콩나물', 'main'), ('무', 'main'), ('당근', 'main'), ('청국장', 'main'), ('계란', 'main'), ('청양고추', 'main'), ('밥', 'main'), 
('돼지고기', 'main'), ('청피망', 'main'), ('적피망', 'main'), ('목이버섯', 'main'), ('죽순', 'main'), ('옥수수', 'main'), 
('오징어', 'main'), ('새우', 'main'), ('조개', 'main'), ('홍합', 'main'), ('양배추', 'main'), ('당면', 'main'), ('숙주', 'main'), 
('팽이버섯', 'main'), ('얇은 고기', 'main'), ('배추', 'main'), ('만두피(시판)', 'main'), ('돼지고기(다짐육)', 'main'), 
('부추', 'main'), ('표고버섯', 'main'), ('새우(중하)', 'main'), ('우동면', 'main'), ('버섯(표고)', 'main'), 
('소고기(갈비살)', 'main'), ('돼지고기(삼겹살)', 'main'), ('해산물믹스', 'main'), ('곤약', 'main'), ('달걀', 'main'), 
('닭고기(허벅지)', 'main'), ('라임', 'main'), ('쌀국수면', 'main'), ('파프리카', 'main'), ('닭고기', 'main'), ('가지', 'main'), 
('버섯(느타리)', 'main'), ('레몬그라스', 'main'), ('라임잎', 'main'), ('코코넛밀크', 'main'), ('시금치', 'main'), 
('감자', 'main'), ('치즈', 'main'), ('상추', 'main'), ('오이', 'main'), ('쌀', 'main'), ('소고기', 'main'), ('토마토', 'main'), 
('생선류', 'main'), ('견과류', 'main'), ('과일류', 'main'), ('아보카도', 'main'), ('퀴노아', 'main'), ('햄', 'main'), 
('라면사리', 'main'), ('소고기(불고기용)', 'main'), ('단무지', 'main'), ('중면', 'main'), ('돼지고기(등심)', 'main'), 
('짜사이', 'main'), ('해물믹스', 'main'), ('김', 'main'), ('생선(고등어/삼치)', 'main'), ('아귀', 'main'), ('미나리', 'main'), 
('미역', 'main'), ('회용생선(광어등)', 'main'), ('어묵', 'main'), ('라면', 'main'), ('라멘면', 'main'), ('돼지뼈', 'main'), 
('닭뼈', 'main'), ('차슈(돼지고기)', 'main'), ('참치캔', 'main'), ('도라지', 'main'), ('순두부', 'main'), ('소면', 'main'), 
('냉면', 'main'), ('배', 'main'), ('파', 'main'), ('신라면', 'main'), ('너구리', 'main'), ('짜파게티', 'main'), ('컵라면', 'main'), 
('용기면', 'main'), ('생라면', 'main'), ('나루토', 'main'), ('차슈', 'main'), ('차돌박이', 'main'), ('완자', 'main'), 
('치킨(통닭)', 'main'), ('치킨가슴살', 'main'), ('치킨윙', 'main'), ('치킨다리', 'main'), ('버거번', 'main'), ('고수', 'main'), 
('숙주나물', 'main'), ('민트', 'main'), ('레몬', 'main'), ('바게트빵', 'main'), ('돼지등뼈', 'main'), ('우거지', 'main'), 
('소고기(양지)', 'main'), ('소갈비', 'main'), ('찹쌀', 'main'), ('대추', 'main'), ('인삼', 'main'), ('고사리', 'main'), 
('토란대', 'main'), ('돼지족발', 'main'), ('돼지목살', 'main'), ('굴', 'main'), ('횟감(광어등)', 'main'), 
('돼지앞다리살', 'main'), ('메밀면', 'main'), ('전복', 'main'), ('단호박', 'main'), ('떡볶이떡', 'main'), ('호박', 'main'), 
('고구마', 'main'), ('삼겹살', 'main'), ('목살', 'main'), ('항정살', 'main'), ('LA갈비', 'main'), ('사과', 'main'), 
('돼지갈비', 'main'), ('소갈비(생갈비)', 'main'), ('닭발', 'main'), ('고등어', 'main'), ('갈치', 'main'), ('삼치', 'main'), 
('조기', 'main'), ('키조개', 'main'), ('가리비', 'main'), ('골뱅이', 'main'), ('곱창', 'main'), ('막창', 'main'), ('쫄면', 'main'), 
('성게', 'main'), ('피망', 'main'), ('찬물', 'main'), ('얼음', 'main'), ('새우(대하)', 'main'), ('생선살(대구)', 'main'), 
('땅콩', 'main'), ('면', 'main'), ('돼지껍질 육수', 'main'), ('가쓰오부시', 'main'), ('카레루', 'main'), ('소바면', 'main'), 
('춘국수면', 'main'), ('문어', 'main'), ('파스타면(스파게티)', 'main'), ('베이컨', 'main'), ('토마토(캔)', 'main'), 
('피자도우', 'main'), ('파인애플', 'main'), ('리조또쌀(아르보리오)', 'main'), ('버섯(포르치니)', 'main'), ('라자냐시트', 'main'), 
('식빵', 'main'), ('양상추', 'main'), ('햄버거번', 'main'), ('소고기패티', 'main'), ('피클', 'main'), ('셀러리', 'main'), 
('돼지어깨살', 'main'), ('브리스킷', 'main'), ('또띠아', 'main'), ('양고기', 'main'), ('라이스페이퍼', 'main'), ('갈비', 'main'), 
('렌틸콩', 'main'), ('면(우동)', 'main'), ('페퍼로니', 'main'), ('콩패티', 'main'), ('버거번(글루텐프리)', 'main'), 
('템페', 'main'), ('닭가슴살', 'main'), ('대게', 'main'), ('킹크랩', 'main'), ('멍게', 'main'), ('생선(흰살)', 'main'), 
('소고기(립아이)', 'main'), ('소고기(등심)', 'main'), ('소고기(안심)', 'main'), ('초밥용 쌀', 'main'), ('연어(회용)', 'main'), 
('무순', 'main'), ('참치(회용)', 'main'), ('장어(구이용)', 'main'), ('광어(회용)', 'main'), ('잉글리시머핀', 'main'), 
('로메인상추', 'main'), ('흰살생선(대구)', 'main'), ('팥', 'main'), ('녹두', 'main'), ('얼그레이티백', 'main'), 
('자몽원액', 'main'), ('만두', 'main'), ('순대', 'main'), ('크루통', 'main'), ('소시지(브라트부어스트)', 'main'), 
('바나나', 'main'), ('프로틴파우더', 'main'), ('베리류', 'main'), ('통밀가루', 'main'), ('두유', 'main');

-- 4. 'seasoning' 재료 추가
INSERT INTO ingredients (ingredient_name, ingredient_category) VALUES
('고추장', 'seasoning'), ('간장', 'seasoning'), ('설탕', 'seasoning'), ('참기름', 'seasoning'), ('식용유', 'seasoning'), 
('고춧가루', 'seasoning'), ('마늘다진것', 'seasoning'), ('소금', 'seasoning'), ('후추', 'seasoning'), ('청주', 'seasoning'), 
('다진마늘', 'seasoning'), ('맛술', 'seasoning'), ('생강즙', 'seasoning'), ('새우젓', 'seasoning'), ('다진생강', 'seasoning'), 
('올리고당', 'seasoning'), ('식초', 'seasoning'), ('굴소스', 'seasoning'), ('물', 'seasoning'), ('생크림', 'seasoning'), 
('물엿', 'seasoning'), ('겨자', 'seasoning'), ('마요네즈', 'seasoning'), ('깨소금', 'seasoning'), ('물전분', 'seasoning'), 
('칠리소스', 'seasoning'), ('케첩', 'seasoning'), ('후춧가루', 'seasoning'), ('베이킹파우더', 'seasoning'), 
('파프리카가루', 'seasoning'), ('마늘가루', 'seasoning'), ('양파가루', 'seasoning'), ('된장', 'seasoning'), 
('올리브오일', 'seasoning'), ('마늘', 'seasoning'), ('생강', 'seasoning'), ('발사믹식초', 'seasoning'), ('드레싱류', 'seasoning'), 
('와인', 'seasoning'), ('허브류', 'seasoning'), ('다시마', 'seasoning'), ('멸치', 'seasoning'), ('꿀', 'seasoning'), 
('국간장', 'seasoning'), ('튀김가루', 'seasoning'), ('월계수잎', 'seasoning'), ('레몬즙', 'seasoning'), ('와사비', 'seasoning'), 
('미림', 'seasoning'), ('미소', 'seasoning'), ('두반장', 'seasoning'), ('마늘소스', 'seasoning'), ('고추기름', 'seasoning'), 
('마라소스', 'seasoning'), ('마라분말', 'seasoning'), ('참깨페이스트', 'seasoning'), ('땅콩버터', 'seasoning'), 
('전분', 'seasoning'), ('춘장', 'seasoning'), ('식초(쌀식초)', 'seasoning'), ('와사비소스', 'seasoning'), ('장어소스', 'seasoning'), 
('다시국물', 'seasoning'), ('다시육수', 'seasoning'), ('오코노미소스', 'seasoning'), ('야키소바소스', 'seasoning'), 
('계피가루', 'seasoning'), ('쿠민', 'seasoning'), ('마늘다짐', 'seasoning'), ('생강다짐', 'seasoning'), ('오향가루', 'seasoning'), 
('누억맘', 'seasoning'), ('피쉬소스', 'seasoning'), ('설탕(팜슈가)', 'seasoning'), ('라임즙', 'seasoning'), 
('타마린드페이스트', 'seasoning'), ('태국바질', 'seasoning'), ('그린커리페이스트', 'seasoning'), ('레드커리페이스트', 'seasoning'), 
('팬낭커리페이스트', 'seasoning'), ('똠얌페이스트', 'seasoning'), ('터메릭', 'seasoning'), ('고수가루', 'seasoning'), 
('카이엔페퍼', 'seasoning'), ('타마린드', 'seasoning'), ('새우페이스트', 'seasoning'), ('오레가노', 'seasoning'), 
('토마토소스', 'seasoning'), ('불고기소스', 'seasoning'), ('갈비소스', 'seasoning'), ('불닭소스', 'seasoning'), 
('김치양념', 'seasoning'), ('와사비마요', 'seasoning'), ('라멘소스', 'seasoning'), ('돈까스소스', 'seasoning'), 
('허브솔트', 'seasoning'), ('영양효모', 'seasoning'), ('해바라기씨오일', 'seasoning'), ('고추가루', 'seasoning'), 
('디종머스터드', 'seasoning'), ('쇼유(간장)', 'seasoning'), ('시오(소금)', 'seasoning'), ('백후추', 'seasoning'), 
('미소(된장)', 'seasoning'), ('갈은깨', 'seasoning'), ('파슬리', 'seasoning'), ('화이트페퍼', 'seasoning'), 
('바닐라에센스', 'seasoning'), ('버터', 'seasoning'), ('가람마살라', 'seasoning'), ('이스트', 'seasoning'), 
('텐푸라소스', 'seasoning'), ('텐츠유소스', 'seasoning'), ('무즙', 'seasoning'), ('케찹', 'seasoning'), ('타르타르소스', 'seasoning'), 
('파마산치즈', 'seasoning'), ('바질', 'seasoning'), ('쌈장', 'seasoning'), ('연겨자', 'seasoning'), ('깻잎', 'seasoning'), 
('쯔유', 'seasoning'), ('페코리노치즈', 'seasoning'), ('모짜렐라치즈', 'seasoning'), ('바질페스토', 'seasoning'), 
('타임', 'seasoning'), ('너트맥', 'seasoning'), ('스테이크소스', 'seasoning'), ('머스타드', 'seasoning'), 
('베셔멜소스', 'seasoning'), ('사워크림', 'seasoning'), ('밀가루', 'seasoning'), ('바비큐소스', 'seasoning'), 
('칠리파우더', 'seasoning'), ('살사소스', 'seasoning'), ('홀랜다이즈소스', 'seasoning'), ('화이트와인식초', 'seasoning'), 
('우스터소스', 'seasoning'), ('화이트소스', 'seasoning'), ('바닐라추출물', 'seasoning'), ('코코아파우더', 'seasoning'), 
('스테비아', 'seasoning'), ('아가베시럽', 'seasoning'), ('타히니', 'seasoning'), ('라면스프', 'seasoning'), 
('건더기스프', 'seasoning'), ('짜장분말', 'seasoning'), ('기름', 'seasoning'), ('휘핑크림', 'seasoning'), 
('카라멜소스', 'seasoning'), ('초콜릿소스', 'seasoning'), ('딸기소스', 'seasoning'), ('바닐라소스', 'seasoning'), 
('연유', 'seasoning'), ('헤이즐넛소스', 'seasoning'), ('비건마요', 'seasoning'), ('코코넛크림', 'seasoning');